### PR TITLE
Added Tooter for SailfishOS

### PR DESCRIPTION
**Pull request by Quent-in**

### CODE REVIEW

**Comment by tleb** [comment]
I feel this is missing two things:

1. A licence ;
2. Installation instructions.

**Comment by smortex** [comment]
@tleb, Tooter is installable through the Jolla store (the single store installed by default on a Jolla phone).

The license is not defined, I openned an issue upstream (dysk0/harbour-tooter#23) but is the license required for adding Tooter to the list?

**Comment by tleb** [comment]
I don't really know the SailfishOS environment, I didn't know how installations work, sorry on this one.

[Without a license](https://choosealicense.com/no-license/), creating a fork of the repo is technically illegal...

**Comment by smortex** [comment]
Well, since it's on GitHub it's legal ([link to TOS](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users)) :wink: 

But ideed you are right, a license is required, hence the issue.

**Comment by tleb** [comment]
I had never read the GitHub TOS, I must admit. :D

I subscribed to the issue, I'll merge as soon as it's closed.

**Comment by dysk0** [comment]
It is added :)

**Comment by smortex** [comment]
@dysk0 Thanks! @Quent-in can you please rebase your changes on top of master?

**Comment by Quent-in** [comment]
Sorry, I didn't get what you wanted me to do :S

**Comment by smortex** [comment]
@Quent-in the file has been modified in the repo after you created the PR, and the modifications conflicts with yours.  The idea is to fix conflicts so that @tleb can merge with a button click :wink: .

For this, you need to move your commit on top of what is currently in the `master` branch of this repo, see [How-to-Rebase-a-Pull-Request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) for more details.

**Comment by Quent-in** [comment]
I cliked Rebase

**Comment by tleb** [comment]
Thanks everyone!

**Pull request merged**
