### PR TITLE
adding cryptocurrency bots (bitcoin,ethereum,monero) and influencer C…

### PR DESCRIPTION
**Pull request by chaica**
- add Bitcoin,Ethereum,Monero News bots
- add Carl Chenet account (french influencer, myself)

### CODE REVIEW

**Comment by tleb** [comment]
The three cryptocurrency bots you add point to 404. Is it normal?

I don't mine adding a personal account but only if it's added by someone else than the person itself.

**Comment by chaica** [comment]
hmmm let me check

**Comment by chaica** [comment]
ok, fixed the urls and removed personal account. Should be fine now.

**Comment by tleb** [comment]
Great, thanks!

**Pull request merged**
